<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK2x1lxq\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK2x1lxq/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerK2x1lxq.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerK2x1lxq\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerK2x1lxq\appDevDebugProjectContainer(array(
    'container.build_hash' => 'K2x1lxq',
    'container.build_id' => '8922f3b8',
    'container.build_time' => 1534055227,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerK2x1lxq');
