<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container36zmx1s\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container36zmx1s/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container36zmx1s.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container36zmx1s\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container36zmx1s\appDevDebugProjectContainer(array(
    'container.build_hash' => '36zmx1s',
    'container.build_id' => 'df6a0170',
    'container.build_time' => 1532019032,
));
